-- 1. テーブルの作成

-- クラステーブル
create table public.classes (
  class_id bigint generated by default as identity not null,
  class_name text not null,
  gacha_meter bigint not null default '0'::bigint,
  constraint classes_pkey primary key (class_id)
) TABLESPACE pg_default;

-- ユーザーテーブル
create table public.users (
  user_id bigint generated by default as identity not null,
  class_id bigint not null,
  user_number numeric not null,
  password text not null,
  role boolean not null,
  title_id bigint null,
  constraint users_pkey primary key (user_id),
  constraint students_class_id_fkey foreign KEY (class_id) references classes (class_id) on update CASCADE on delete CASCADE,
  constraint users_title_id_fkey foreign KEY (title_id) references titles (title_id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;

-- お題テーブル
create table public.genres (
  genre_id bigint generated by default as identity not null,
  genre_name text not null,
  constraint genres_pkey primary key (genre_id)
) TABLESPACE pg_default;

-- お題テンプレテーブル
create table public.template_topics (
  template_topic_id bigint generated by default as identity not null,
  genre_id bigint not null,
  template_topic_content text not null,
  constraint template_topics_pkey primary key (template_topic_id),
  constraint template_topics_genre_id_fkey foreign KEY (genre_id) references genres (genre_id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;

-- お題決定後テーブル
create table public.topics (
  topic_id bigint generated by default as identity not null,
  class_id bigint not null,
  genre_id bigint not null,
  template_topic_id bigint null,
  topic_content text not null,
  created_at timestamp with time zone not null default now(),
  constraint topics_pkey primary key (topic_id),
  constraint topics_class_id_fkey foreign KEY (class_id) references classes (class_id) on update CASCADE on delete CASCADE,
  constraint topics_genre_id_fkey foreign KEY (genre_id) references genres (genre_id) on update CASCADE on delete CASCADE,
  constraint topics_template_topic_id_fkey foreign KEY (template_topic_id) references template_topics (template_topic_id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;

-- 投稿テーブル
create table public.posts (
  post_id bigint generated by default as identity not null,
  class_id bigint not null,
  user_id bigint not null,
  topic_id bigint not null,
  post_content text not null,
  created_at timestamp with time zone not null default now(),
  is_posted boolean not null default false,
  constraint posts_pkey primary key (post_id),
  constraint posts_class_id_fkey foreign KEY (class_id) references classes (class_id) on update CASCADE on delete CASCADE,
  constraint posts_topic_id_fkey foreign KEY (topic_id) references topics (topic_id) on update CASCADE on delete CASCADE,
  constraint posts_user_id_fkey foreign KEY (user_id) references users (user_id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;

-- リアクションログテーブル
create table public.reaction_logs (
  reaction_id bigint generated by default as identity not null,
  post_id bigint not null,
  user_id bigint not null,
  genre_id bigint not null,
  reaction_1 bigint not null,
  reaction_2 bigint not null,
  reaction_3 bigint not null,
  reaction_4 bigint not null,
  created_at timestamp with time zone not null default now(),
  constraint reaction_logs_pkey primary key (reaction_id),
  constraint reaction_logs_genre_id_fkey foreign KEY (genre_id) references genres (genre_id) on update CASCADE on delete CASCADE,
  constraint reaction_logs_post_id_fkey foreign KEY (post_id) references posts (post_id) on update CASCADE on delete CASCADE,
  constraint reaction_logs_user_id_fkey foreign KEY (user_id) references users (user_id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;

-- ガチャアイテムテーブル
create table public.items (
  item_id bigint generated by default as identity not null,
  item_name text not null,
  item_image text not null,
  constraint items_pkey primary key (item_id)
) TABLESPACE pg_default;

-- 動物園の配置保存用テーブル
create table public.zoo_placements (
  placement_id bigint generated by default as identity not null,
  item_id bigint not null,
  area_id bigint null,
  class_id bigint null,
  constraint zoo_placements_pkey primary key (placement_id),
  constraint zoo_placements_area_id_fkey foreign KEY (area_id) references zoo_areas (area_id) on update CASCADE on delete CASCADE,
  constraint zoo_placements_class_id_fkey foreign KEY (class_id) references classes (class_id) on update CASCADE on delete CASCADE,
  constraint zoo_placements_item_id_fkey foreign KEY (item_id) references items (item_id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;

-- 動物園の配置テーブル
create table public.zoo_areas (
  area_id bigint generated by default as identity not null,
  area text not null,
  constraint zoo_areas_pkey primary key (area_id)
) TABLESPACE pg_default;

-- 称号テーブル
create table public.titles (
  title_id bigint generated by default as identity not null,
  title_name text not null,
  constraint titles_pkey primary key (title_id)
) TABLESPACE pg_default;

-- NGワードテーブル
create table public.ng_words (
  word_id bigint generated by default as identity not null,
  word text not null,
  created_at timestamp with time zone not null default now(),
  constraint ng_words_pkey primary key (word_id)
) TABLESPACE pg_default;




-- 2. ダミーデータの挿入
-- classesテーブル
INSERT INTO public.classes (class_name) VALUES
  ('1年1组'),
  ('1年2組'),
  ('2年1組'),
  ('2年2組'),
  ('3年1組'),
  ('3年2組'),
  ('4年1組'),
  ('4年2組'),
  ('5年1組'),
  ('6年1組');


-- users テーブルへのダミーデータ挿入
INSERT INTO public.users (class_id, user_number, password, role, title_id) VALUES
  -- ■ クラス 1（10人: 先生1人 + 児童9人）
  (1, 0, 'teacher_pass1', false, NULL),
  (1, 1, 'pass_101', true, NULL),
  (1, 2, 'pass_102', true, NULL),
  (1, 3, 'pass_103', true, NULL),
  (1, 4, 'pass_104', true, NULL),
  (1, 5, 'pass_105', true, NULL),
  (1, 6, 'pass_106', true, NULL),
  (1, 7, 'pass_107', true, NULL),
  (1, 8, 'pass_108', true, NULL),
  (1, 9, 'pass_109', true, NULL),

  -- ■ クラス 2（10人: 先生1人 + 児童9人）
  (2, 0, 'teacher_pass2', false, NULL),
  (2, 1, 'pass_201', true, NULL),
  (2, 2, 'pass_202', true, NULL),
  (2, 3, 'pass_203', true, NULL),
  (2, 4, 'pass_204', true, NULL),
  (2, 5, 'pass_205', true, NULL),
  (2, 6, 'pass_206', true, NULL),
  (2, 7, 'pass_207', true, NULL),
  (2, 8, 'pass_208', true, NULL),
  (2, 9, 'pass_209', true, NULL),

  -- ■ クラス 3（10人: 先生1人 + 児童9人）
  (3, 0, 'teacher_pass3', false, NULL),
  (3, 1, 'pass_301', true, NULL),
  (3, 2, 'pass_302', true, NULL),
  (3, 3, 'pass_303', true, NULL),
  (3, 4, 'pass_304', true, NULL),
  (3, 5, 'pass_305', true, NULL),
  (3, 6, 'pass_306', true, NULL),
  (3, 7, 'pass_307', true, NULL),
  (3, 8, 'pass_308', true, NULL),
  (3, 9, 'pass_309', true, NULL);