-- 1. クラステーブル
create table public.classes (
  class_id bigint generated by default as identity not null,
  class_name text not null,
  gacha_meter bigint not null default '0'::bigint,
  constraint classes_pkey primary key (class_id)
);

-- 2. お題ジャンルテーブル
create table public.genres (
  genre_id bigint generated by default as identity not null,
  genre_name text not null,
  constraint genres_pkey primary key (genre_id)
);

-- 3. お題テンプレテーブル
create table public.template_topics (
  template_topic_id bigint generated by default as identity not null,
  genre_id bigint not null,
  template_topic_content text not null,
  constraint template_topics_pkey primary key (template_topic_id),
  constraint template_topics_genre_id_fkey foreign KEY (genre_id) references genres (genre_id) on update CASCADE on delete CASCADE
);

-- 4. ガチャアイテムテーブル
create table public.items (
  item_id bigint generated by default as identity not null,
  item_name text not null,
  item_image text not null,
  constraint items_pkey primary key (item_id)
);

-- 5. 動物園の配置テーブル (エリア)
create table public.zoo_areas (
  area_id bigint generated by default as identity not null,
  area text not null,
  constraint zoo_areas_pkey primary key (area_id)
);

-- 6. 称号テーブル
create table public.titles (
  title_id bigint generated by default as identity not null,
  title_name text not null,
  constraint titles_pkey primary key (title_id)
);

-- 7. NGワードテーブル
create table public.ng_words (
  word_id bigint generated by default as identity not null,
  word text not null,
  created_at timestamp with time zone not null default now(),
  constraint ng_words_pkey primary key (word_id)
);

-- 8. ユーザーテーブル (classes, titles を参照)
create table public.users (
  user_id bigint generated by default as identity not null,
  class_id bigint not null,
  user_number numeric not null,
  password text not null,
  role boolean not null,
  title_id bigint null,
  constraint users_pkey primary key (user_id),
  constraint students_class_id_fkey foreign KEY (class_id) references classes (class_id) on update CASCADE on delete CASCADE,
  constraint users_title_id_fkey foreign KEY (title_id) references titles (title_id) on update CASCADE on delete CASCADE
);

-- 9. お題決定後テーブル (classes, genres, template_topics を参照)
create table public.topics (
  topic_id bigint generated by default as identity not null,
  class_id bigint not null,
  genre_id bigint not null,
  template_topic_id bigint null,
  topic_content text not null,
  created_at timestamp with time zone not null default now(),
  constraint topics_pkey primary key (topic_id),
  constraint topics_class_id_fkey foreign KEY (class_id) references classes (class_id) on update CASCADE on delete CASCADE,
  constraint topics_genre_id_fkey foreign KEY (genre_id) references genres (genre_id) on update CASCADE on delete CASCADE,
  constraint topics_template_topic_id_fkey foreign KEY (template_topic_id) references template_topics (template_topic_id) on update CASCADE on delete CASCADE
);

-- 10. 投稿テーブル (classes, users, topics を参照)
create table public.posts (
  post_id bigint generated by default as identity not null,
  class_id bigint not null,
  user_id bigint not null,
  topic_id bigint not null,
  post_content text not null,
  created_at timestamp with time zone not null default now(),
  is_posted boolean not null default false,
  constraint posts_pkey primary key (post_id),
  constraint posts_class_id_fkey foreign KEY (class_id) references classes (class_id) on update CASCADE on delete CASCADE,
  constraint posts_topic_id_fkey foreign KEY (topic_id) references topics (topic_id) on update CASCADE on delete CASCADE,
  constraint posts_user_id_fkey foreign KEY (user_id) references users (user_id) on update CASCADE on delete CASCADE
);

-- 11. リアクションログテーブル (posts, users, genres を参照)
create table public.reaction_logs (
  reaction_id bigint generated by default as identity not null,
  post_id bigint not null,
  user_id bigint not null,
  genre_id bigint not null,
  reaction_1 bigint not null,
  reaction_2 bigint not null,
  reaction_3 bigint not null,
  reaction_4 bigint not null,
  created_at timestamp with time zone not null default now(),
  constraint reaction_logs_pkey primary key (reaction_id),
  constraint reaction_logs_genre_id_fkey foreign KEY (genre_id) references genres (genre_id) on update CASCADE on delete CASCADE,
  constraint reaction_logs_post_id_fkey foreign KEY (post_id) references posts (post_id) on update CASCADE on delete CASCADE,
  constraint reaction_logs_user_id_fkey foreign KEY (user_id) references users (user_id) on update CASCADE on delete CASCADE
);

-- 12. 動物園の配置保存用テーブル (items, zoo_areas, classes を参照)
create table public.zoo_placements (
  placement_id bigint generated by default as identity not null,
  item_id bigint not null,
  area_id bigint null,
  class_id bigint null,
  constraint zoo_placements_pkey primary key (placement_id),
  constraint zoo_placements_area_id_fkey foreign KEY (area_id) references zoo_areas (area_id) on update CASCADE on delete CASCADE,
  constraint zoo_placements_class_id_fkey foreign KEY (class_id) references classes (class_id) on update CASCADE on delete CASCADE,
  constraint zoo_placements_item_id_fkey foreign KEY (item_id) references items (item_id) on update CASCADE on delete CASCADE
);